# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZTJlM2M5OWI4ZmY3YTk5NWVkYTZhYzQwODNlODM2OTFkMGIxMDUzODYxODJkMGJlMDQ5ZDJjNDMzNzAxOTRjZjVmMTljZWM0ODdmMmMwOWUwMzU2MzY4ZGE0YmVlZWZkMDcyNjk0MzdjNzVhMDA1Y2IwNTA0Y2JlY2E3M2IyYmE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
